server:
    port: 8761  # Eureka 服务器默认端口

eureka:
    client:
        register-with-eureka: false  # 不将自身注册到 Eureka 服务器
        fetch-registry: false        # 不从 Eureka 服务器获取注册信息
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

    server:
        enable-self-preservation: false  # 关闭自我保护模式（开发环境用）
    instance:
        hostname: localhost  # Eureka 服务器主机名
